### ISSUE TITLE
packages not found

### ISSUE THREAD

**Issue by iDestin** [didi/react-tmap#1]
似乎在公开的npm源上搜索不到这个包

![image](https://user-images.githubusercontent.com/36811055/167073740-e6086dc3-0fd9-4b4b-91dc-1ada463628dd.png)

**Comment by iblq** [comment]
是的，刚刚开源，这个包还没发布，今天可以解决

**Comment by iblq** [comment]
@iDestin 问题已修复哈，项目可以正常启动。
由于目前还在开源流程中，npm 包都没有正式发布。
