### ISSUE TITLE
服务类附加库问题

### ISSUE THREAD

**Issue by weitangli** [didi/react-tmap#3]
请问怎么使用服务类附加库功能，我想使用根据地址关键字搜索坐标？

服务类附加库：https://lbs.qq.com/webApi/javascriptGL/glGuide/service

**Comment by iblq** [comment]
@weitangli ，你好，TMap 组件已支持 `libraries` props ，可传入一个 `string[]` 来加载附加库，且默认支持 `visualization` `tools`  `geometry` 三个库，可查看文档中[自定义属性](https://didi.github.io/react-tmap/#/components/map)

**Comment by weitangli** [comment]
明白，那我怎么才能获取附加库？

**Comment by weitangli** [comment]
找到原因了。
是因为`import { TMap } from '@map-component/react-tmap';`的`TMap`与附加库的`TMap.service.Search`中的`TMap`重复了。
我的处理方法是`import`时取个别名。

**Comment by iblq** [comment]
是的是的，我也刚发现了，可以使用 `window.TMap.service`,这确实是个问题，再想想优化一下命名问题

**Comment by weitangli** [comment]
也行，免得取别名了。
