### ISSUE TITLE
请教下，`@map-component/tmap-types` 库是贵司的库吗？

### ISSUE THREAD

**Issue by xhwgood** [didi/react-tmap#6]
如果是的话，`@map-component/tmap-types` 能否开源下？因为贵司的 `react-tmap` 不太完善，我项目里使用的时候有很多问题，但感觉 `@map-component/tmap-types` 我使用是挺不错的，想提个 PR 完善一下类型定义，谢谢

**Comment by iblq** [comment]
@xhwgood  `@map-component/tmap-types` 的开源地址是 [@map-component/tmap-types](https://github.com/didi/tmap-types) ; 有问题可以提出来持续完善， 感谢关注😄

**Comment by xhwgood** [comment]
已提交 PR

**Comment by xhwgood** [comment]
> @xhwgood `@map-component/tmap-types` 的开源地址是 [@map-component/tmap-types](https://github.com/didi/tmap-types) ; 有问题可以提出来持续完善， 感谢关注😄

在那个仓库 @ 不了你，想问下我代码是不是有什么要修改的？如果没有的话何时可以合并 😄

**Comment by iblq** [comment]
@xhwgood  已经合并，更新了npm包
